config/routes.rb
Rails.application.routes.draw do

  root "students#index"

  resources :students
  resources :courses
  resources :classrooms

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord

  # hooks
  before_create :set_entry_at

  # relations
  belongs_to :student, foreign_key: 'students_id'
  belongs_to :course, foreign_key: 'courses_id'

  # validations
  validates_uniqueness_of :students_id, scope: :courses_id

  def set_entry_at
    self.entry_at = DateTime.now.in_time_zone
  end

end

app/models/course.rb
class Course < ApplicationRecord
  extend EnumerateIt

  has_enumeration_for :status, with: CourseStatus

  # relations
  has_many :classrooms

  # validations
  validates_presence_of :name
end

app/models/student.rb
class Student < ApplicationRecord
  extend EnumerateIt

  has_enumeration_for :status, with: StudentStatus

  # relations
  has_many :classrooms

  # validations
  validates_uniqueness_of :register_number
  validates_presence_of :name, :register_number, :status
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController

  def index
    @classrooms = Classroom.all
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.create classroom_params
    respond_with @classroom, location: -> { classrooms_path }
  end

  def destroy
    if Classroom.where(id: params[:id]).destroy_all
      redirect_to classrooms_path
    else
    end
  end

  protected

  def classroom_params
    params.require(:classroom).permit(:students_id, :courses_id)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  respond_to :html

  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create course_params
    respond_with @course, location: -> { courses_path }
  end

  def edit
  end

  def update
    @course.update_attributes course_params
    respond_with @course, location: -> { courses_path }
  end

  def destroy
    if @course.destroy
    end

    redirect_to course_path
  end

  protected

  def set_course
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit(:name, :description, :status)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  respond_to :html

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create students_create_params
    respond_with @student, location: -> { students_path }
  end

  def edit
  end

  def update
    @student.update_attributes students_update_params
    respond_with @student, location: -> { students_path }
  end

  def destroy
    if @student.destroy
    end

    redirect_to students_path
  end

  protected

  def set_student
    @student = Student.find params[:id]
  end

  def students_create_params
    params.require(:student).permit(:name, :register_number, :status)
  end

  def students_update_params
    params.require(:student).permit(:name, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classrooms/index.html.slim
.container
  h1 Classrooms List

  .row
    == link_to "New Classroom", new_classroom_path, class: 'btn btn-primary'

  table.table.table-hover
    thead
      tr
        td Student
        td Course
        td Entry At
        td Actions

    - @classrooms.each do |classroom|
        tr
          td = classroom.student.name
          td = classroom.course.name
          td = classroom.entry_at.strftime("%d/%m/%Y %H:%m")
          td == link_to "Delete", classroom_path(classroom), method: :delete

app/views/classrooms/new.html.slim
.container
  h1 New Classroom

  - if @classroom.errors.any?
    .alert.alert-danger
      - @classroom.errors.full_messages.each do |message|
        | *
        = message
        br

  == form_for @classroom do |f|
      .form-group
        = f.label :student, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.collection_select :students_id, Student.all, :id, :name, {}, {class: 'form-control required'}

      .form-group
        = f.label :course, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.collection_select :courses_id, Course.all, :id, :name, {}, {class: 'form-control required'}

      .form-group
        .col.sm-offset-2.col-sm-10
          = f.submit 'Create Course', :class => 'btn btn-primary'

app/views/courses/edit.html.slim
.container
  h1 Edit Course

  - if @course.errors.any?
    .alert.alert-danger
      - @course.errors.full_messages.each do |message|
        | *
        = message
        br

  == form_for @course, url: {controller: :courses, action: :update} do |f|
      .form-group
        = f.label :name, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :name, class: 'form-control required'

      .form-group
        = f.label :description, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :description, class: 'form-control'

      .form-group
        .col-sm-10
          = f.check_box :status, {}, CourseStatus::ACTIVE, CourseStatus::INACTIVE
          |   Active?

      .form-group
        .col.sm-offset-2.col-sm-10
          = f.submit 'Update Course', :class => 'btn btn-primary'

app/views/courses/index.html.slim
.container
  h1 Courses List

  .row
    == link_to "New Course", new_course_path, class: 'btn btn-primary'

  table.table.table-hover
    thead
      tr
        td Name
        td Description
        td Status

    - @courses.each do |course|
        tr
          td == link_to course.name, edit_course_path(course)
          td = course.description.truncate(25)
          td = course.status_humanize

app/views/courses/new.html.slim
.container
  h1 New Course

  - if @course.errors.any?
    .alert.alert-danger
      - @course.errors.full_messages.each do |message|
        | *
        = message
        br

  == form_for @course do |f|
      .form-group
        = f.label :name, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :name, class: 'form-control required'

      .form-group
        = f.label :description, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :description, class: 'form-control'

      .form-group
        .col-sm-10
          = f.check_box :status, {}, CourseStatus::ACTIVE, CourseStatus::INACTIVE
          |   Active?

      .form-group
        .col.sm-offset-2.col-sm-10
          = f.submit 'Create Course', :class => 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title IsTest
    == csrf_meta_tags

    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          == link_to "[iS] Test", root_path, class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              == link_to "Students", students_path
            li
              == link_to "Courses", courses_path
            li
              == link_to "Classrooms", classrooms_path
        /! /.nav-collapse

    == yield

app/views/students/edit.html.slim
.container
  h1 Edit Student

  - if @student.errors.any?
    .alert.alert-danger
      - @student.errors.full_messages.each do |message|
        | *
        = message
        br

  == form_for @student, url: {controller: :students, action: :update} do |f|
      .form-group
        = f.label :name, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :name, class: 'form-control required'

      .form-group
        = f.label :register_number, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :register_number, class: 'form-control required'

      .form-group
        .col-sm-10
          = f.check_box :status, {}, StudentStatus::ACTIVE, StudentStatus::INACTIVE
          |   Active?

      .form-group
        .col.sm-offset-2.col-sm-10
          = f.submit 'Update Student', :class => 'btn btn-primary'

app/views/students/index.html.slim
.container
  h1 Students List

  .row
    == link_to "New Student", new_student_path, class: 'btn btn-primary'

  table.table.table-hover
    thead
      tr
        td Name
        td Register
        td Status

    - @students.each do |student|
        tr
          td == link_to student.name, edit_student_path(student)
          td = student.register_number
          td = student.status_humanize

app/views/students/new.html.slim
.container
  h1 New Student

  - if @student.errors.any?
    .alert.alert-danger
      - @student.errors.full_messages.each do |message|
        | *
        = message
        br

  == form_for @student do |f|
      .form-group
        = f.label :name, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :name, class: 'form-control required'

      .form-group
        = f.label :register_number, class: 'col-sm-2 control-label'

        .col-sm-10
          = f.text_field :register_number, class: 'form-control required'

      .form-group
        .col-sm-10
          = f.check_box :status, {}, StudentStatus::ACTIVE, StudentStatus::INACTIVE
          |   Active?

      .form-group
        .col.sm-offset-2.col-sm-10
          = f.submit 'Create Student', :class => 'btn btn-primary save'